version: 2
jobs:
  "node-13":
    docker:
      - image: circleci/node:13
    working_directory: ~/fuxor
    steps:
      - checkout

      - run: npm install
      # run tests!
      - run: npm test
      - run: npm run coverage
      - run: npm run report
      - store_test_results:
          path: ~/fuxor/reports
  "node-12":
    docker:
      - image: circleci/node:12
    working_directory: ~/fuxor
    steps:
      - checkout

      - run: npm install
      # run tests!
      - run: npm test
      - run: npm run coverage
      - run: npm run report
      - store_test_results:
          path: ~/fuxor/reports

  "node-10":
    docker:
      - image: circleci/node:10
    working_directory: ~/fuxor
    steps:
      - checkout

      - run: npm install
      # run tests!
      - run: npm test
      - run: npm run report
      - store_test_results:
          path: ~/fuxor/reports

  "node-8":
    docker:
      - image: circleci/node:8
    working_directory: ~/fuxor
    steps:
      - checkout

      - run: npm install
      # run tests!
      - run: npm test
      - run: npm run report
      - store_test_results:
          path: ~/fuxor/reports

workflows:
  version: 2
  build:
    jobs:
      - "node-13"
      - "node-12"
      - "node-10"
      - "node-8"
